### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [ClaireE93/recommendation-nation#3]
`ColumnSet` is a heavy static type. It should be created just once and then reused, as documented in the API everywhere :wink:

**Comment by ClaireE93** [comment]
Hi, thank you for the feedback! I'm having trouble setting dynamic columns so I can reuse ColumSet for the insert operation. I tried:
```
const cs = new pgp.helpers.ColumnSet([
  '?product_id',
  '?user_id',
  '?rating',
  '?category',
  '?category_id',
]);

const heapInsert = (array, tableName) => {
  const insert = pgp.helpers.insert(array, cs, tableName);
  return db.none(insert);
};
```

But according to the API the cnd flag is ignored by insert operations and I get an error that the property names don't exist. 

I also tried the following according to issue [#306](https://github.com/vitaly-t/pg-promise/issues/306)

```
const optional = name => ({
  name: Array.isArray(name) ? name[0] : name, 
  def: { toPostgres: () => 'DEFAULT', _rawType: true },
  skip: c => !c.exists,
});
const cs = new pgp.helpers.ColumnSet([
  optional('product_id'),
  optional('user_id'),
  optional('rating'),
  optional('category'),
  optional('category_id'),
]);
```

And am getting ```ERROR in setup { error: column "product_id" of relation "users" does not exist```

**Comment by vitaly-t** [comment]
>  I get an error that the property names don't exist.

What is the desired behavior in your case?

**Comment by ClaireE93** [comment]
I have multiple tables that I need to heap insert into that all have different columns. If I'm going to reuse the ColumnSet object for insertion, then I need to be able to have it only define columns that are passed in to my ```heapInsert``` function. I would like to have something like this:
```
const cs = new pgp.helpers.ColumnSet([
  '?product_id',
  '?user_id',
  '?rating',
  '?category',
  '?category_id',
]);

const heapInsert = (array, tableName) => {
  const insert = pgp.helpers.insert(array, cs, tableName);
  return db.none(insert);
};
```

and call it like so...
```
heapInsert([{user_id: 5}, {user_id: 6}, {user_id: 7}], 'users');
heapInsert([{product_id: 1}, {product_id: 2}, {product_id: 3}], 'products');
heapInsert([{product_id: 1, user_id: 5, rating: 1.3}], 'purchase');
```

**Comment by vitaly-t** [comment]
That would be quite misusing type `ColumnSet`, which is intended to represent columns of a single table.

You should create a separate `ColumnSet` for each table statically. Is there a reason you are not following the standard usage pattern?

**Comment by ClaireE93** [comment]
That is what I had been doing before, I thought your initial issue here was that I should reuse ColumnSet? Did I misunderstand your initial issue?

**Comment by vitaly-t** [comment]
Yeah, you completely misunderstood me. What I meant was - you should create each `ColumnSet` once, statically, and then reuse those, as opposed to what you were doing - recreating them inline on each call.

**Comment by ClaireE93** [comment]
Okay got it. I will make the change and close this issue after my next PR. Thanks for your input and help!
